### ISSUE TITLE
Make animation slideOutLeft slide back and forth?

### ISSUE THREAD

**Issue by eabigelow** [daneden/animate.css#1012]
Hi--

This is a terrific animation tool. Thank you so much!

I was wondering, is it possible to have slideOutLeft go out left and then return? In this case, the animation would simply go left, then right, back and forth, forever.

Is that possible? Thank you very much for any thoughts, and again, a great css tool!

**Comment by WarenGonzaga** [comment]
Hi @eabigelow thank you! We appreciate it... btw I'm gonna look into it... let me give you updates.

**Comment by eabigelow** [comment]
Thank you very much!

**Comment by WarenGonzaga** [comment]
@eltonmesquita got it!

**Comment by eabigelow** [comment]
Thank you very much! Do I download this from the main zip/repository?

**Comment by WarenGonzaga** [comment]
@eabigelow I'm still working on it... just add a new feature to #998

**Comment by WarenGonzaga** [comment]
@eabigelow done! Added and updated the lightSpeed animations look for commit 6f47729 in #1029

**Comment by WarenGonzaga** [comment]
@eltonmesquita done! kindly review

**Comment by WarenGonzaga** [comment]
@eabigelow I guess adding slide back and forth effect is not needed in the slide animations... since the name speaks itself... I think you are referring to ```bounceOutLeft``` if I add the back and forth animation to slideOutLeft it would be redundant for bounceOutLeft since they are the same.

let us know if you need any help so @eltonmesquita can close this...

**Comment by eabigelow** [comment]
Ok thanks you so much again. Much appreciated. Do you have a paypal I can send $30 us to? 😀

Alan

Alan Bigelow, Ph.D.
Professor, Dept. of Interdisciplinary Studies
Medaille College
Buffalo, NY

**Comment by WarenGonzaga** [comment]
@eabigelow you can buy me a coffee instead ;) 
https://buymeacoff.ee/warengonzaga

**Comment by WarenGonzaga** [comment]
> Ok thanks you so much again. Much appreciated. Do you have a paypal I can send $30 us to?  Alan Alan Bigelow, Ph.D. Professor, Dept. of Interdisciplinary Studies Medaille College Buffalo, NY
> […](#)
> On Mar 2, 2020, at 4:57 PM, Waren Gonzaga ***@***.***> wrote: ﻿ @eabigelow done! Added and updated the lightSpeed animations look for commit [6f47729](https://github.com/daneden/animate.css/commit/6f47729d2bc19c8bb1f767689ca7413f7481a1fd) in #1029 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @eabigelow, my mistake... I mentioned this issue for a fix which is not. I need your confirmation if you are looking for `bounceOutLeft` animation or do you need something like plain slide animation that doing back in fort slide instead of bouncing... let me know so I can add it to the current development.

**Comment by eabigelow** [comment]
I am good as is. I see that the effect is really sufficient as is. But I am happy to buy you a cup of coffee! 

Alan 

Alan Bigelow, Ph.D.
Professor, Dept. of Interdisciplinary Studies
Medaille College
Buffalo, NY

**Comment by WarenGonzaga** [comment]
Thank you @eabigelow for buying me 5 cups of coffee! I really love it...
