### ISSUE TITLE
[Feature Request] Simple Typing Animation

### ISSUE THREAD

**Issue by kevtan** [daneden/animate.css#1035]
It would awesome if Animate.css had a basic typing animation! Other projects like Typed.js have more heavy-weight scripting-based solutions that easy get unwieldy when you just need a simple typing animation, and a stylesheet-based solution would be a nice, light-weight alternative.

**Comment by WarenGonzaga** [comment]
@eltonmesquita @daneden what do you think?

For me, we want to make the Animate.css as natural as possible we don't want to make animate.css become heavy-weight something like typed.js...

We will take a look into this and discuss it.

**Comment by kevtan** [comment]
There are a few CSS-based solutions to this online already but the code for it isn't very clean or general enough to handle many use cases. In addition, I think this would be a very popular animation for developers (e.g. showcase what to type in the shell, etc.). I would be happy to contribute a typing animation if you guys think it's something that would fit in Animate.css!

**Comment by WarenGonzaga** [comment]
> There are a few CSS-based solutions to this online already but the code for it isn't very clean or general enough to handle many use cases. In addition, I think this would be a very popular animation for developers (e.g. showcase what to type in the shell, etc.). I would be happy to contribute a typing animation if you guys think it's something that would fit in Animate.css!

Let's wait for @eltonmesquita and @daneden to discuss it.

**Comment by daneden** [comment]
Hey @kevtan! Thanks for the suggestion. I think this kind of animation is pretty specific and actually non-trivial to implement in CSS alone. We have to consider different typeface character widths, effects like pausing on punctuation, etc.

Since there are alternate, dedicated libraries already out there for this kind of animation, I’d prefer not to introduce it to Animate.css, which is intentionally focused on simpler animations.
