### ISSUE TITLE
Support for browserify?

### ISSUE THREAD

**Issue by alexweissman** [daneden/animate.css#1041]
When I attempt to load this package with browserify, it fails with an `Unexpected character '@'` error. I'm wondering if this has to do with the fact that the `main` entry point in `package.json` is a CSS file?

I've noticed that some pure CSS packages have added a `browserify` entry to their `package.json` that might address this. For example: https://github.com/KyleAMathews/react-spinkit/pull/11/files

**Comment by WarenGonzaga** [comment]
@alexweissman thank you for reporting this... I don't think if this is useful for our development. What do you think @eltonmesquita ?

**Comment by eltonmesquita** [comment]
It's being so long since I've used browserify, but I think that you just need a module or plugin to import a css library. It shouldn't need anything on our side, but I might be wrong.

Sorry, but I don't feel very keen to add this as it's the first time it has been asked and browserify exist for a long time.
