### ISSUE TITLE
Animations not working properly in mozilla

### ISSUE THREAD

**Issue by TresV** [daneden/animate.css#319]
First of all, thank you for your hard work to create this incredible library!
I've found out that the animations appear/work differently in mozilla, they seem to be quite faster and not as smooth as they are in chrome, what my be the cause? Could it be because of the vendor?

**Comment by eltonmesquita** [comment]
@jpburn Did you try the new FF version? Does the problem persist? If so, what's the FF's version and OS?

**Comment by rajanand** [comment]
The animation in the background (connecting the dots) seems fast in Firefox 35 Windows 7.

**Comment by joshi-mehul** [comment]
can you show the link where is the problem?

**Comment by rajanand** [comment]
@joshi-mehul http://thecodehome.tk/

**Comment by Yeswanth-JG** [comment]
There is a problem with firefox compared to chrome.

> Firefox creates a __single thread__ in the system to run all its tasks.Whereas, __Chrome__ utilizes multi-threading functionality. It creates separate process threads for each opened tab.! 

_So that, resource utilization is poor in firefox rather than chrome._

Taking this as a cause, when you are running animations, there will be a continuous _CPU ram & processor usage_. In the case of single-thread, cpu scheduling will be very slow & creates issue. In multi-thread, scheduling algorithm considers only the __thread/process__ related to the tab 'in which had opened your web page.!

This makes the page animations / transitions & executing JS (requires RAM) makes slow.!

You are running animations on CANVAS, which uses abundant JS, that firefox makes

* more RAM usage
* more processor allotment.

---
**NOTE: *So, based on the processor, application speed depends*.**

**Comment by joshi-mehul** [comment]
You're right at some point, but both the engines using Non-blocking IO
which is the feature of JS(makes it faster) It doesn't mean that Firefox is
slower in JS execution. on my machine most of the times Chrome sucks but
Firefox never. So it depends still.

Thanks

On Mon, Mar 2, 2015 at 10:19 AM, J Govind Yeswanth <notifications@github.com

**Comment by joshi-mehul** [comment]
In my firefox it's showing well just, In my firefox it's showing well,
please clear your cache and completely install the fresh copy of the
firefox.

Thanks

**Comment by Yeswanth-JG** [comment]
@joshi-mehul...
Few more reasons
* Recent version of firefox got more futuristic. So, its requires more resources to run.
* This issue will also depends on the system processor ( even the brand!)
* Chrome will fail some times, because it uses multi-threading. Some older intel processors & AMD processors aren't that good in multi-threading...!
* To make firefox running good, we should use processor with high IPC with high single core frequency & more __RAM__(RAM usage compared to that of _Chrome_). But to run chrome, we need processor with 2 or more cores & better multi-threading scheduling algorithm.!

**Comment by Yeswanth-JG** [comment]
@TresV::
Go to taskbar & kill processors that are using more memory ( not processor) & try running Firefox in safe mode. (ADDONS disbaled!)

OR

Now kill the processes taking more processor & try running firefox in safe mode.!

------
Please follow the above two & reply here with the speed in each action ( after clearing RAM & after clearing processor!)

**Comment by daneden** [comment]
This is probably outside of our control. Sounds like a browser bug/issue. Closing.
