### ISSUE TITLE
funny look to ZoomInDown

### ISSUE THREAD

**Issue by ludasmokva** [daneden/animate.css#379]
Hi. 
First and foremost wonderful wonderful resource! It looks great on your website.
I'm attempting to incorporate it into my own design and am having a weird problem.
My ZoomInDown looks more like a 'ZoomIn-from-the-Right' :)

This is my fiddle: https://jsfiddle.net/6u3goq8s/1/
The result is still  ok, but I am wondering if I am doing something wrong, or if the codes got mixed up somehow. This animation looks different on your site.

Still, thank you very much for a great resource.

**Comment by daneden** [comment]
@ludasmokva this is because the transformation is happening from the center of the element, but the text is not centered, so it appears to be coming in at an angle.

Here’s a version with the text centered: https://jsfiddle.net/6u3goq8s/2/

Another fix would be to have the `.tag-1` element set as `display: inline-block;` so that it doesn’t occupy the full width of the page.

**Comment by ludasmokva** [comment]
You closed the comment, but I just wanted to thank you for your quick
response. Your example looks exactly like I wanted my effect to look.
I wanted to email you back that everything looks perfect now, but
unfortunately I am having some problems with positioning in my design once
I 'center' the tag.  But the effect itself looks great and I'll just have
to figure the positioning out... but I didn't want to wait any longer to
express my appreciation.
So once again, thank you.

**Comment by daneden** [comment]
@ludasmokva you’re very welcome!

![](http://gif.daneden.me/high-five-ish.gif)
