### ISSUE TITLE
FlipIn fix for iOS pre 8.3

### ISSUE THREAD

**Issue by firedev** [daneden/animate.css#382]
Hi,

Any suggestions how to fix disappearing elements with FlipInY for iOS pre-8.3? I have beta 8.3 installed and it works fine. However on earlier devices elements disappear after animation is completed.

**Comment by laurensnl** [comment]
Same problem here on flipInX.

**Comment by fatbattk** [comment]
Not sure if related.
`flipInX`, `flipInY` does not work on **iOS Safari** specifically. Works on iOS Chrome app. `flip` however works fine.

 Here is an example I made,
http://jsbin.com/munohuceku/1/edit?html,js,output

**Comment by fseminario** [comment]
Getting same issue on flip* not showing on iOS 8.1 safari

**Comment by snack8** [comment]
Changing all of the **from** to **0%** in the style sheet(animate.css/animate.min.css) seems to fix this problem. It only seems to be a problem for the flip animations, which leads me to believe it has something to do with the perspective attribute since they are the only animations that make use of it.

**Comment by laurensnl** [comment]
Thanks! I'll give it a try.

**Comment by procodeing** [comment]
@mesge This could be a problem

**Comment by mesge** [comment]
Seems more likely that this is related to #298. I have a feeling it's a browser bug.
