### ISSUE TITLE
Animate pseudo-elements (:after)

### ISSUE THREAD

**Issue by timhecker** [daneden/animate.css#385]
Hi,
is it possible to animate a pseudo element :after, absolute positioned?

**Comment by alamops** [comment]
Loot at this: http://stackoverflow.com/a/12985111/2886567

**Comment by drdogbot7** [comment]
It's 2019 now and, yes, CSS animations can be applied to pseudo elements just like any other element… maybe at one time this was not the case.

https://codepen.io/drdogbot7/pen/aeEmNx

**_This package_** (animate.css) won't work with pseudo elements, because there is no way to add the necessary classes to a pseudo element.
