### ISSUE TITLE
SyntaxError: illegal character animate.min.css:1:0

### ISSUE THREAD

**Issue by smpdesignmedia** [daneden/animate.css#400]
hi,

i fount illegal character error in animate.min.css "javascript console".

Error :
SyntaxError: illegal character animate.min.css:1:0

**Comment by procodeing** [comment]
@smpdesignmedia hello, could you post a pen explaining your problem?

**Comment by polarathene** [comment]
Chrome reports `Uncaught SyntaxError: Unexpected token ILLEGAL` in the console when using animate.css 3.4.0 via [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.4.0/animate.min.css). The offending line is `@charset "UTF-8";/*!`

I have tried the example: `<h1 class="animated infinite bounce">Example</h1>` and nothing seems to happen. Aha, made a silly mistake and used a script tag instead of link for some reason :P

**Comment by procodeing** [comment]
oh, its probibly mad because of the non seperation of the comment and the first line

**Comment by polarathene** [comment]
@procodeing I thought that at first, but turns out I was too tired and used a script tag instead of a link tag. @smpdesignmedia probably did the same?

**Comment by procodeing** [comment]
probably, plus, it's not that big of a deal at all
