### ISSUE TITLE
Why is the .zoomIn animation animated from 0% to 50%?

### ISSUE THREAD

**Issue by leolopes** [daneden/animate.css#437]
I ask this question because I usually set initial styles for animated elements so that they don't flicker on pageload. For example:
<code><pre>.cssanimations element.animated {
    opacity: 0;
}</pre></code>

Then, I use js to add the .zoomIn class, that should result in an element with <code>opacity: 1</code>.

As I noticed, because <code>opacity: 1</code> is at 50% of the zoomIn animation, even though there are no further declarations, the result is a zero opacity element.

I fixed it by changing the 50% keyframe to 100%.

However, if there is any reason why it is originally set to 50%, I'd like to understand.

Thanks.

**Comment by daneden** [comment]
If you have `animation-fill-mode: both` set, that should help avoid the flickering issue without needing to set the opacity yourself. Otherwise, try setting `animation-fill-mode: forwards`. Basically, even if the opacity declaration were set at 100% of the keyframe, you'd still experience the same issue so long as you're setting `opacity: 0;` in your own CSS.
