### ISSUE TITLE
It's not you, it's Chrome.

### ISSUE THREAD

**Issue by bwente** [daneden/animate.css#443]
Chromes CSS animations are getting worse. Any idea how to degrade gracefully?

Chrome 43.0 - Mac OSX

as seen on https://daneden.github.io/animate.css/

**Comment by eltonmesquita** [comment]
This can be an isolated issue, like an extension making your Chrome slow or a regression in the version. I do get a little struggling in Chrome stable now, but not in Canary. Maybe it'll be fixed in the next stable versions.

The only thing to do is wait and see, as you'd have to do some UA sniffing to disable animations only in Chrome and this is a really bad idea.

**Comment by bwente** [comment]
THANK YOU!!!
I have been trying to fix this issue for hours. It was an extension!

SEE lets you view the web as a user with a visual impairment might.
https://chrome.google.com/webstore/detail/see/dkihcccbkkakkbpikjmpnbamkgbjfdcn
