### ISSUE TITLE
Add license text with the repo.

### ISSUE THREAD

**Issue by biwin** [daneden/animate.css#445]
As the readme says the project is MIT licensed, there in no license agreement(s) is included. Please consider adding one. 

MIT license text here : http://opensource.org/licenses/MIT

**Comment by daneden** [comment]
Not true—the license is in the CSS file itself, which is all that many people will use.

**Comment by ilmente** [comment]
Hi @daneden,
my compliments for the really nice work.

I have to ask the same thing that @biwin already did: can you please add a license manifest into your repo? While it's true that the css (that contains the link to license) is the object of the MIT terms, a manifest containing those terms is not available in your package.

I'm working for a company, and we are scanning our FOSS in order to make clear view regarding legal issues. We're selling a commercial product that uses your module. From our lawyer prospective, a potential customer could require to see the manifest inside the module: even if linked, a proper MIT license require a copyright holder at the beginning, something that is in your css, but formally wrong because there is no manifest to check.

Can you add it?
Thanks a lot.
Best.
Alessandro
