### ISSUE TITLE
span cant be animated

### ISSUE THREAD

**Issue by godlatro** [daneden/animate.css#515]
<h1 class="headerpup cen"><span class="anik animated swing">W</span>ORD</h1>

IT wont work. 
SWING, TADA, bounce, pulse etc..

IT will work
FLASH

<span class="anik animated swing">W</span> will be animate if its @display:inline-block;@

**Comment by MHanslo** [comment]
Historically, span elements can't be animated with CSS. In order to animate them, you'll need to give them a display property. Obviously `display: block;` will give you undesirable effects, so assigning `display: inline-block` would be a better choice, and solve the issue.

Having animate.css assign `display: inline-block;` on span elements will be undesirable; it can potentially break layouts.

**Comment by daneden** [comment]
Either giving it a `display` value or a non-static `position` value will allow a `span` element to be animated.

**Comment by chhagandaspawar** [comment]
but i already animated to span tag
but here problem is i wanna animate to second span h2 
so i want any shakeble animation effect
