### ISSUE TITLE
opacity

### ISSUE THREAD

**Issue by ayfati01** [daneden/animate.css#548]
hi, whenever i set an animated element to have opacity, it will always run with out having the opacity. please help

**Comment by bennetthardwick** [comment]
Hi! 

If you use `color: rgba(r, g, b, a);` instead of `color: #rgb; opacity: a;` in your CSS then it won't be affected. However, if you're trying to animate an image or something else, it would probably be easier to edit the opacity of the image in an image editor like GIMP and then export the image as a png. 

You haven't mentioned much in your comment but I'm going to assume that you're using a fadeIn, fadeOut or other animation that changes the opacity of the element you're animating. Because animate.css animates the opacity, what normally will happen is that it will use your specified opacity as the starting opacity, and will then transition to the opacity set by animate.css for the fadeIn / fadeOut effect. So any animation that isn't an entrance, an exit or an animation that uses opacity should work fine for you.

I hope this helps!
