### ISSUE TITLE
How to repeat chained animations?

### ISSUE THREAD

**Issue by ghost** [daneden/animate.css#599]
I'm animating letters for a preloader. For example: "L O A D" all letters have a delay, then bounce in sequence. If I add "infinite" class, they start bouncing randomly after the first chain has completed. This is not desired.

How to start the animation over at the beginning? Sorry, I'm not good in Javascript.

This is what I have so far....

`
setInterval( function () {

```
    $('#letter-l').addClass( $animate_css ).css( '-webkit-animation-delay', '0s' ).one( $animate_end,
        function() { $(this).removeClass( $animate_css ); }
    );
    $('#letter-o').addClass( $animate_css ).css( '-webkit-animation-delay', '.3s' ).one( $animate_end,
        function() { $(this).removeClass( $animate_css ); }
    );
    $('#letter-a').addClass( $animate_css ).css( '-webkit-animation-delay', '.6s' ).one( $animate_end,
        function() { $(this).removeClass( $animate_css ); }
    );
    $('#letter-d').addClass( $animate_css ).css( '-webkit-animation-delay', '.9s' ).one( $animate_end,
        function() { $(this).removeClass( $animate_css ); }
    );

}, 1000);
```

`

Thanks

**Comment by tnga** [comment]
Hi! i think one of your problem is the timed interval. You use `1000ms` which equal to `1s`; but your animation timeline is `0s + 0.3s + 0.6s + 0.9s` = `1.8s`. So your setInterval function will always apply before the end of your animations and may cause an unexpected behavior. Try to set the timed interval according to your animation timeline.

**Comment by eltonmesquita** [comment]
Closing this as it's stale.
