### ISSUE TITLE
Demo site broken

### ISSUE THREAD

**Issue by odesey** [daneden/animate.css#659]
Not sure if you are aware but the demo site is broken, none of the animations are working on Chrome v54 Linux.

**Comment by eltonmesquita** [comment]
I can't test it as I have no 64bit Linux distro at my disposal, but I think this is an issue related to Chrome or to GPU acceleration in Chrome.
Animate CSS should work in any capable browser that supports 3d transform and animations. As you're using Linux, it's kinda of usual to not have 3d acceleration turned off because of the lack of drivers. As the system can't use the GPU for transforms, I think that Chrome might be having a bad time with animations. But it's just a guess.

**Comment by odesey** [comment]
Just tested it on a Mac and it works as expected...guess the latest versions of Chrome for Linux (v54 & v55) are broken. 

When you select a new animation from the drop down nothing happens and clicking the animate button refreshes the page instead of executing the selected animation.

The actual animations still work fine in practice however, its just the implementation on the demo site that seems to be broken.

**Comment by odesey** [comment]
This has been fixed with an updated version of Chrome on Linux.
