### ISSUE TITLE
animation.css delay the ion-items from ion-list

### ISSUE THREAD

**Issue by JoanJosep33** [daneden/animate.css#751]
I am trying to create an effect from a list of elements with Ionic. I am using the library animate.cssand I would like to do a delay between the elements which form the list. In this example it shows what exactly I would like to do.The problem is that I don't know how to do it on css to set a dinamicly delay for each item.Here is my code:
`<ion-content padding>
 <ion-card>
  <ion-card-header>
   <ion-card-title>Rooms Avaliables</ion-card-title>
  </ion-card-header>
 <ion-list>
  <ion-item class="animated fadeInLeft" *ngFor="let room of rooms">
    {{room |json}}
  </ion-item>
 </ion-list>
</ion-card>
</ion-content>`

But what I get, obviously, are all the items fadeIn left at the same time.

Thank you a lot, any suggestion would be appreciated it.

**Comment by zyj123** [comment]
1

At 2017-10-21 18:46:28, "JoanJosep33" <notifications@github.com> wrote:


I am trying to create an effect from a list of elements with Ionic. I am using the library animate.cssand I would like to do a delay between the elements which form the list. In this example it shows what exactly I would like to do.The problem is that I don't know how to do it on css to set a dinamicly delay for each item.Here is my code:
<ion-content padding> <ion-card> <ion-card-header> <ion-card-title>Rooms Avaliables</ion-card-title> </ion-card-header> <ion-list> <ion-item class="animated fadeInLeft" *ngFor="let room of rooms"> {{room |json}} </ion-item> </ion-list> </ion-card> </ion-content>

But what I get, obviously, are all the items fadeIn left at the same time.

Thank you a lot, any suggestion would be appreciated it.

**Comment by eltonmesquita** [comment]
If your list is not dynamic and you know how many items there'll be in it, jus use `:nth-child()` and set the delay individually. Sass/Less/Stylus would be of great help here.
If your list is dynamic, you'll have to use some javascript for it. If I'm not wrong, Ionic uses Angular, so the best idea would be to research for a way to do it using Angular itself. We can't give support to third part libraries (that would be humanly impossible). Maybe Stackoverflow can help you.
