### ISSUE TITLE
[Safari 11] Animated Elements have weird backgrounds 

### ISSUE THREAD

**Issue by foxnoodles** [daneden/animate.css#755]
Ok so this happens only in Safari 11(haven't tried on older ones)  

basically the title is self explanatory but here's the gif: 

![animate css safari11 bug](https://user-images.githubusercontent.com/1949828/32148850-9d2235d6-bd15-11e7-9441-121e538330d8.gif)

you get this weird backgrounds right until the animation finishes.. then they disappear, but you can still see some of it left behind the letters. 

Any ideas?

**Comment by foxnoodles** [comment]
any ideas? anyone?

**Comment by eltonmesquita** [comment]
Can you please post a URL? It'll be hard to help without anything live.

**Comment by foxnoodles** [comment]
I can't cuz it's a commercial project and I can't replicate the bug with a minified example.
Here's some additional info: 

Content scrolls inside the DIV(with overflow-y: hidden and X auto) so it's not scrolling the actual body element. 

structure goes like this:

`<body><div name=main scrollable wrapper> <div name=some other shit></div> <div name=content></div></div></body>`

all of them have background colors... that's pretty much it...  
The bug goes away if I assign a white background color to everything (note: not transparent but actual white) 

I think it has something to do with Safari's new rendering engine.. when there are a lot of composite layers and some transforms happen.. it starts to flicker.. basically this is render flickering.

**Comment by eltonmesquita** [comment]
Yeah, seems like a nasty Safari bug. Try to set a transform like `transform: translateZ(0)` at some flickering elements and see if it helps

**Comment by foxnoodles** [comment]
Tried that didn't help :/  Even tried disabling the backface visibility(cuz it obviously composites the parent divs bg colors) that didn't help either.. we are doomed.

**Comment by eltonmesquita** [comment]
Nasty bugs need nasty solution. Try some of these:
- Use `will-change: transform, opacity ([read about it here](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)) on animating elements;
- Add `clip-path: polygon(0 0, 100% 0, 100% 100%, 0% 100%);` to some flickering element. It'll have no visual impact but might fix it;
- Try to set the colors in rgb or hsl instead of hex.

**If `will-change` or `clip-path` work, try applying it only on as few elements as possible as you can have some performance problems.**

To be honest, last time I had a similar problem with Safari it happened with one specific version only, I think it was 9.x. Any other version, 8- or 10+ had no problem. The only solution was to do some nasty UA sniffing and disabling the features only on this specific version.

Lately Safari has being so unpleasant to deal with... It's kinda sad.

**Comment by foxnoodles** [comment]
This is nightmare :/ none of this work.. even tried custom indents for will-change... -_-

**Comment by eltonmesquita** [comment]
Try to see if it affects only some specific Safari versions. IF so, I think that using UA sniffing to disable the animations on Safari might be the solution.

If you need help on this, just give a heads up.

**Comment by eltonmesquita** [comment]
I'm closing this as there was no more response for about 1 month. Feel free to reopen it if there's some news on this issue.

**Comment by epidemicsad** [comment]
Hey. I have the same issue. Does anyone found any solution for this? I've checked this problem on few different mac's and it occurs only on one of them... Safari version on all devices is the same. As foxnoodles said, it's a nightmare, none of solutions given here is not working.

**Comment by foxnoodles** [comment]
Sadly I couldn't find a solution, just disabled it in Safari 11 (happens only there)
