### ISSUE TITLE
Image gets shrank to the width of the parent div

### ISSUE THREAD

**Issue by phackwer** [daneden/animate.css#826]
Hi.

I have an image that is bigger than the parent div (and that I need to center with CSS). When I apply animations (except flash), the image gets shrink to the size of the parent div. 

Any ideas why?

**Comment by eltonmesquita** [comment]
You're probably centering it with `translation` which is used by animated.css and end up being overwritten. Just center the image with another technique like `text-align: center` on the parent. Another option is to put the image inside another element and translate this parent element instead of the image itself.
