### ISSUE TITLE
animations loading twice?

### ISSUE THREAD

**Issue by laurencefass** [daneden/animate.css#913]
some content slides in twice in some places and once in others. im only using css no javascript. this is not happening on all elements and appears quite unpredictable.

**Comment by eltonmesquita** [comment]
Hello.
Could you please detail the issue? Also, providing a reduced case on codepen will make it easier to help you.

**Comment by javaskript** [comment]
Try adding

`visibility: hidden;`

to your animated element.

**Comment by WarenGonzaga** [comment]
@laurencefass please provide us a codepen version so we can check your issue and solve it. Thank you!

**Comment by laurencefass** [comment]
The animation is not actually happening twice. The problem arises trying to assign classes in JQuery and does not appear when I hard-code classes into html elements. Also it also only noticeable to the first element on the page.

I think this is a limitation with jquery not an issue with animate.css (though it does effect it) and there appears no way (I can find) to assign classes BEFORE the page is rendered. 

My workaround is to fadeIn the entire body element slower than the animate.css effects so the user can't see the first element swap happening.

**Comment by WarenGonzaga** [comment]
Hi, @laurencefass since it is a jquery related issue and you already said affecting it with our animate.css then it's not totally an issue to animate.css that's why we are going to remove the jquery as a way to use with animate.css we've discussed this earlier, we have decided to replace all jquery samples and demo with vanilla JS. Please refer to this issue #835 Have a good day!

Anyway, thanks for your workaround it might be helpful to others in the future. ;) can we close this now?

**Comment by laurencefass** [comment]
thanks for your help ill reissue if i see further problems but i think this is a known problem with jquery.
