### ISSUE TITLE
animated div position wrong

### ISSUE THREAD

**Issue by alainbelez** [daneden/animate.css#924]
im trying to animate the dropdown list and the position is wrong.

https://stackblitz.com/edit/angular-zteyj1?embed=1&file=app/dropdown-basic.html

**Comment by eltonmesquita** [comment]
This happens because animate.css uses transforms and will override the element's initial transform. You'll have to find a way to wrap that element and add the animation to this wrap.

I'll close this as it's unrelated to an issue tracker. If you need more help, stackoverflow is a much better place as this should be used with issues and bugs, not with question related to usage. You'll get way more help there!

Thanks!
