### ISSUE TITLE
transform: translate3d disregarding z-index

### ISSUE THREAD

**Issue by NotJustThatGuy** [daneden/animate.css#947]
I discovered that translate3d which is used by most (if not, all) animations and z-index that i am using in an ::after element isn't really good together for translate3d disregards the z-index. Is there a work around this?

**Comment by eltonmesquita** [comment]
Hi. This is a CSS question and not directly related to animate.css. I let this open to see if someone would take the time to answer it, but it didn't happen.

This kind of question should be made on Stackoverflow and not in the library's issue tracker, which is dedicated to issues and improvement of the library itself.

I'm closing this issue because of this.
