### ISSUE TITLE
Making Animations Wait Till Visible

### ISSUE THREAD

**Issue by uandiweb** [daneden/animate.css#951]
Great project. Is it possible to add animation to the footer, and make it wait till the footer is visible? Without it, most users will miss the animation effects.

**Comment by eltonmesquita** [comment]
You'll need an animate on scroll library like [AOS](https://michalsnik.github.io/aos/).

I'm closing this as it's unrelated to the library itself.

**Comment by AlchemyUnited** [comment]
@eltonmesquita - Um. It would help if this was stated up front. That is, when reading the examples - and not seeing anything otherwise - the impression is your library is tied to the CSS class animated. That is, add the class and the magic happens. In the broader context of similar libraries,  JS,  lazyload, etc to me it seem like a fair assumption and a reasonable expectation.

But it doesn't work that way.  At all. 

p.s. fwiw, I've just lost a significant number of hours because of this. All because the docs don't make it clear that a key feature is not available. So  sad.
