### ISSUE TITLE
animation-delay not working with decimals

### ISSUE THREAD

**Issue by ekntrtmz** [daneden/animate.css#994]
Can someone confirm that `animation-delay` is not working with decimals?

I am using animate.css with Vue.js passing animate.css classes to the enter-active-class of my transitions, like this:

```
<transition
   appear
   mode="out-in"
   enter-active-class="animated fadeIn delay-0.5s"
>
<span v-if="show">Foo</span>
</transition>
```

If so, is there any workarround?

**Comment by eltonmesquita** [comment]
There's no decimals for delays. These classes are just helpers and are not extensive, any delay that is not listed on the read me, is the developer's reasonability to add on hers/his project. There's no plans to add more delays actually.

To solve your problems, just create new classes on you project with the wanted delay using the `animation-delay` property, such as:
```css
.delay-05 {
  animation-delay: 0.5s;
}
```

**Comment by hdehal** [comment]
@eltonmesquita Thank you for your work on this library.

Wanted to bubble this up -- looks like more than a handful of users would like to leverage delays using the library instead of writing additional CSS, e.g. for delays <1s above and beyond what's in the readme.

https://github.com/animate-css/animate.css/pull/1019
https://github.com/animate-css/animate.css/issues/1017
https://github.com/animate-css/animate.css/issues/994

Can you confirm if this would be possible, or if your re: custom CSS properties [here](https://github.com/animate-css/animate.css/issues/1017#issuecomment-593125424) was launched since March 2020?

Thanks in advance!
